version: "3.9"

services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - .env.release
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/todolist
    command: >
      sh -c "python manage.py runbot"
  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
  postgres:
    image: postgres:latest
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    restart: always
    env_file:
      - .env.release
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/todolist
    ports:
      - "8000:8000"
  migrations:
    build:
      context: .
    env_file:
      - .env.release
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env.release:/todolist/.env
    command: >
      sh -c "python manage.py migrate"

volumes:
  pg_data:
