# Generated by Django 4.1.3 on 2022-12-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_alter_goal_description_alter_goal_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
    ]
