# Generated by Django 4.1.3 on 2022-12-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='command',
            field=models.CharField(max_length=20, null=True, verbose_name='Текущая команда'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(max_length=20, verbose_name='Код верификации'),
        ),
    ]
