# Generated by Django 4.1.3 on 2022-12-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_command_alter_tguser_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='user_id',
            new_name='user',
        ),
    ]
